### ISSUE TITLE
Need a method to test/wait for service to be access inside cluster

### ISSUE THREAD

**Issue by randmonkey** [Kong/kubernetes-testing-framework#331]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

When we deploy some addons or services, we need a tool to detect or wait for the service to be ready to serve. For example, when we deploy `kuma` addon in the cluster, we need to wait for kuma's webhook service to be ready before we create CRDs in kuma. So, we need a method to test whether a service could be accessed inside the testing kubernetes cluster. 

### Proposed Solution

- provide a solution that runs a `Job` with some images to test the TCP connection periodically, and complete the job when the TCP connection is created.

### Acceptance Criteria

 could call a method in KTF to test if a service/address could be accessed in the test cluster by:
  - [ ] (At least) TCP connection
  - [ ] GET/POST to an HTTP URL
  - [ ] TLS connection (with CA/client cert)
  - [ ] GET/POST by an HTTPS URL (with a CA/client cert)

**Comment by mflendrich** [comment]
Reason: Fixing this test flake https://github.com/Kong/kubernetes-ingress-controller/issues/2735 requires that KTF waits for Redis availability.

**Comment by randmonkey** [comment]
test flakiness that could be resolved or debugged by this issue:
- https://github.com/Kong/kubernetes-ingress-controller/issues/2733
- https://github.com/Kong/kubernetes-ingress-controller/issues/2735
- https://github.com/Kong/gateway-operator/issues/100

**Comment by randmonkey** [comment]
Proposed solution:
- create an image `tcptest` that exits with code 0 when successfully connected to a TCP address, and retry until a configurable timeout, and exit with non-0 code when reached timeout
- when testing a service, create a `Job` using this image and wait for completion of that job

**Comment by rainest** [comment]
Kubernetes should (effectively) provide this for us, since we can check Deployment status. This isn't directly linked to the Service status (though you can figure it out by querying labels), but that's usually a non-issue since we just know the correct Deployment in our tests.

For https://github.com/Kong/gateway-operator/issues/100 we are checking the Deployment readiness, but are still failing. Why the Deployment is ready without the webhook is unclear, since we do add a readiness requirement using controller-runtime and use its standard webhook server tooling, which I'd hope starts the server before saying it's ready.

 For https://github.com/Kong/kubernetes-ingress-controller/issues/2733 we are not checking the Deployment readiness or retrying the apply yet. This may be affected by the same Deployment-ready-webhook-not-ready problem as the above.

https://github.com/Kong/kubernetes-ingress-controller/issues/2735 is unclear, since we do check the Deployment readiness and the problem in question would definitely prevent it from becoming ready. We may have seen an unrelated issue in the initial report, where something else happened that did allow it to get further on in the test.

**Comment by randmonkey** [comment]
> Kubernetes should (effectively) provide this for us, since we can check Deployment status. This isn't directly linked to the Service status (though you can figure it out by querying labels), but that's usually a non-issue since we just know the correct Deployment in our tests.
> 
> For [Kong/gateway-operator#100](https://github.com/Kong/gateway-operator/issues/100) we are checking the Deployment readiness, but are still failing. Why the Deployment is ready without the webhook is unclear, since we do add a readiness requirement using controller-runtime and use its standard webhook server tooling, which I'd hope starts the server before saying it's ready.
> 
> For [Kong/kubernetes-ingress-controller#2733](https://github.com/Kong/kubernetes-ingress-controller/issues/2733) we are not checking the Deployment readiness or retrying the apply yet. This may be affected by the same Deployment-ready-webhook-not-ready problem as the above.
> 
> [Kong/kubernetes-ingress-controller#2735](https://github.com/Kong/kubernetes-ingress-controller/issues/2735) is unclear, since we do check the Deployment readiness and the problem in question would definitely prevent it from becoming ready. We may have seen an unrelated issue in the initial report, where something else happened that did allow it to get further on in the test.

The reason why we need this when kubernetes has already provided readiness probe:
- The readiness probe is not a strong enough proof that the service is ready on the pod/deployment side, especially when the source code of deployment/pod is not controlled by us (for example, kuma deployment)
- Even when the server side is ready to serve, the service may not be accessible because we still need to access the service through `kube-proxy`. One example is this issue: [Kong/kubernetes-ingress-controller#2760](https://github.com/Kong/kubernetes-ingress-controller/issues/2760). We checked for the webhook to be ready, but the test may still fail with 
```
Internal error occurred: failed calling webhook "validations.kong.konghq.com": failed to call webhook: Post "[https://webhook-kong-validations-gateway.kong-system.svc:443/?timeout=10s](https://webhook-kong-validations-gateway.kong-system.svc/?timeout=10s)": context deadline exceeded
```

The most likely reason for error `context deadline exceeded` is that the kube-proxy has not installed the rule for routing the traffic yet. So we still need an approach here to wait for the service to be ready.
